#!/usr/bin/env bash
# Summary: Configure the shell environment for hugoenv
# Usage: eval "$(hugoenv init - [--no-rehash] [<shell>])"

set -e
[ -n "$HUGOENV_DEBUG" ] && set -x

# Provide hugoenv completions
if [ "$1" = "--complete" ]; then
  echo -
  echo --no-rehash
  echo bash
  echo fish
  echo ksh
  echo zsh
  exit
fi

print=""
no_rehash=""
for args in "$@"
do
  if [ "$args" = "-" ]; then
    print=1
    shift
  fi

  if [ "$args" = "--no-rehash" ]; then
    no_rehash=1
    shift
  fi
done

shell="$1"
if [ -z "$shell" ]; then
  shell="$(ps -p "$PPID" -o 'args=' 2>/dev/null || true)"
  shell="${shell%% *}"
  shell="${shell##-}"
  shell="${shell:-$SHELL}"
  shell="${shell##*/}"
  shell="${shell%%-*}"
fi

root="${0%/*}/.."

if [ -z "$print" ]; then
  case "$shell" in
  bash )
    if [ -f "${HOME}/.bashrc" ] && [ ! -f "${HOME}/.bash_profile" ]; then
      profile='~/.bashrc'
    else
      profile='~/.bash_profile'
    fi
    ;;
  zsh )
    profile='~/.zshrc'
    ;;
  ksh )
    profile='~/.profile'
    ;;
  fish )
    profile='~/.config/fish/config.fish'
    ;;
  * )
    profile='your profile'
    ;;
  esac

  { echo "# Load hugoenv automatically by appending"
    echo "# the following to ${profile}:"
    echo
    case "$shell" in
    fish )
      echo 'status --is-interactive; and hugoenv init - fish | source'
      ;;
    * )
      printf 'eval "$(hugoenv init - %s)"\n' "$shell"
      ;;
    esac
    echo
  } >&2

  exit 1
fi

mkdir -p "${HUGOENV_ROOT}/"{shims,versions}

case "$shell" in
fish )
  echo "set -gx PATH '${HUGOENV_ROOT}/shims' \$PATH"
  echo "set -gx HUGOENV_SHELL $shell"
;;
* )
  echo 'export PATH="'${HUGOENV_ROOT}'/shims:${PATH}"'
  echo "export HUGOENV_SHELL=$shell"

  completion="${root}/completions/hugoenv.${shell}"
  if [ -r "$completion" ]; then
    echo "source '$completion'"
  fi
;;
esac

if [ -z "$no_rehash" ]; then
  echo 'command hugoenv rehash 2>/dev/null'
fi

commands=(`hugoenv-commands --sh`)
case "$shell" in
fish )
  cat <<EOS
function hugoenv
  set command \$argv[1]
  set -e argv[1]

  switch "\$command"
  case ${commands[*]}
    hugoenv "sh-\$command" \$argv|source
  case '*'
    command hugoenv "\$command" \$argv
  end
end
EOS
  ;;
ksh )
  cat <<EOS
function hugoenv {
  typeset command
EOS
  ;;
* )
  cat <<EOS
hugoenv() {
  local command
EOS
  ;;
esac

if [ "$shell" != "fish" ]; then
IFS="|"
cat <<EOS
  command="\${1:-}"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  case "\$command" in
  ${commands[*]})
    eval "\$(hugoenv "sh-\$command" "\$@")";;
  *)
    command hugoenv "\$command" "\$@";;
  esac
}
EOS
fi
