#!/usr/bin/env bash
#
# Summary: Set or show the local application-specific Hugo version
#
# Usage: hugoenv local <version>
#        hugoenv local --unset
#
# Sets the local application-specific Hugo version by writing the
# version name to a file named `.hugo-version'.
#
# When you run a Hugo command, hugoenv will look for a `.hugo-version'
# file in the current directory and each parent directory. If no such
# file is found in the tree, hugoenv will use the global Hugo version
# specified with `hugoenv global'. A version specified with the
# `HUGOENV_VERSION' environment variable takes precedence over local
# and global versions.
#
# <version> should be a string matching a Hugo version known to hugoenv.
# The special version string `system' will use your default system Hugo.
# Run `hugoenv versions' for a list of available Hugo versions.

set -e
[ -n "$HUGOENV_DEBUG" ] && set -x

# Provide hugoenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec hugoenv-versions --bare
fi

HUGOENV_VERSION="$1"

if [ "$HUGOENV_VERSION" = "--unset" ]; then
  rm -f .hugo-version
elif [ -n "$HUGOENV_VERSION" ]; then
  hugoenv-version-file-write .hugo-version "$HUGOENV_VERSION"
else
  if version_file="$(hugoenv-version-file "$PWD")"; then
    hugoenv-version-file-read "$version_file"
  else
    echo "hugoenv: no local version configured for this directory" >&2
    exit 1
  fi
fi
