#!/usr/bin/env bash
#
# Summary: Run an executable with the selected Hugo version
#
# Usage: hugoenv exec <command> [arg1 arg2...]
#
# Runs an executable by first preparing PATH so that the selected Hugo
# version's `bin' directory is at the front.
#
# For example, if the currently selected Hugo version is 0.10.26:
#   hugoenv exec bundle install
#
# is equivalent to:
#   PATH="$HUGOENV_ROOT/versions/0.10.26/bin:$PATH" bundle install

set -e
[ -n "$HUGOENV_DEBUG" ] && set -x

# Provide hugoenv completions
if [ "$1" = "--complete" ]; then
  exec hugoenv-shims --short
fi

HUGOENV_VERSION="$(hugoenv-version-name)"
HUGOENV_COMMAND="$1"

if [ -z "$HUGOENV_COMMAND" ]; then
  hugoenv-help --usage exec >&2
  exit 1
fi

export HUGOENV_VERSION
HUGOENV_COMMAND_PATH="$(hugoenv-which "$HUGOENV_COMMAND")"
HUGOENV_BIN_PATH="${HUGOENV_COMMAND_PATH%/*}"

OLDIFS="$IFS"
IFS=$'\n' scripts=(`hugoenv-hooks exec`)
IFS="$OLDIFS"
for script in "${scripts[@]}"; do
  source "$script"
done

shift 1
if [ "$HUGOENV_VERSION" != "system" ]; then
  export PATH="${HUGOENV_BIN_PATH}:${PATH}"
fi
exec -a "$HUGOENV_COMMAND" "$HUGOENV_COMMAND_PATH" "$@"
