#!/usr/bin/env bash
# Summary: List hook scripts for a given hugoenv command
# Usage: hugoenv hooks <command>

set -e
[ -n "$HUGOENV_DEBUG" ] && set -x

# Provide hugoenv completions
if [ "$1" = "--complete" ]; then
  echo exec
  echo rehash
  echo version-name
  echo version-origin
  echo which
  exit
fi

HUGOENV_COMMAND="$1"
if [ -z "$HUGOENV_COMMAND" ]; then
  hugoenv-help --usage hooks >&2
  exit 1
fi

if ! enable -f "${BASH_SOURCE%/*}"/hugoenv-realpath.dylib realpath 2>/dev/null; then
  if [ -n "$HUGOENV_NATIVE_EXT" ]; then
    echo "hugoenv: failed to load \`realpath' builtin" >&2
    exit 1
  fi
READLINK=$(type -p greadlink readlink 2>/dev/null | head -n1)
if [ -z "$READLINK" ]; then
  echo "hugoenv: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

realpath() {
  local cwd="$PWD"
  local path="$1"
  local name

  while [ -n "$path" ]; do
    name="${path##*/}"
    [ "$name" = "$path" ] || cd "${path%/*}"
    path="$(resolve_link "$name" || true)"
  done

  echo "${PWD}/$name"
  cd "$cwd"
}
fi

IFS=: hook_paths=($HUGOENV_HOOK_PATH)

shopt -s nullglob
for path in "${hook_paths[@]}"; do
  for script in "$path/$HUGOENV_COMMAND"/*.bash; do
    realpath "$script"
  done
done
shopt -u nullglob
