#!/usr/bin/env bash
# Usage: hugoenv version-file [<dir>]
# Summary: Detect the file that sets the current hugoenv version
set -e
[ -n "$HUGOENV_DEBUG" ] && set -x

target_dir="$1"

find_local_version_file() {
  local root="$1"
  while ! [[ "$root" =~ ^//[^/]*$ ]]; do
    if [ -s "${root}/.hugo-version" ]; then
      echo "${root}/.hugo-version"
      return 0
    fi
    [ -n "$root" ] || break
    root="${root%/*}"
  done
  return 1
}

if [ -n "$target_dir" ]; then
  find_local_version_file "$target_dir"
else
  find_local_version_file "$HUGOENV_DIR" || {
    [ "$HUGOENV_DIR" != "$PWD" ] && find_local_version_file "$PWD"
  } || echo "${HUGOENV_ROOT}/version"
fi
