#!/usr/bin/env bash
#
# Summary: Set or show the global Hugo version
#
# Usage: hugoenv global <version>
#
# Sets the global Hugo version. You can override the global version at
# any time by setting a directory-specific version with `hugoenv local'
# or by setting the `HUGOENV_VERSION' environment variable.
#
# <version> should be a string matching a Hugo version known to hugoenv.
# The special version string `system' will use your default system Hugo.
# Run `hugoenv versions' for a list of available Hugo versions.

set -e
[ -n "$HUGOENV_DEBUG" ] && set -x

# Provide hugoenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec hugoenv-versions --bare
fi

HUGOENV_VERSION="$1"
HUGOENV_VERSION_FILE="${HUGOENV_ROOT:?}/version"

if [ "$1" = "--unset" ]; then
  exec rm -f "$HUGOENV_VERSION_FILE"
fi

if [ -n "$HUGOENV_VERSION" ]; then
  hugoenv-version-file-write "$HUGOENV_VERSION_FILE" "$HUGOENV_VERSION"
else
  hugoenv-version-file-read "$HUGOENV_VERSION_FILE" || echo system
fi
